### ISSUE TITLE
Improve error message building with Java 9

### ISSUE THREAD

**Issue by aro** [enonic/xp-gradle-plugin#13]
When building with Java JDK 9 it fails with a confusing error message.
Improve the message or fix it so that the build works with Java 9.

Reported in [Discuss](https://discuss.enonic.com/t/error-when-using-gradlew-deploy-for-tutorial-could-not-determine-java-version-from-9-0-4/1435).

**Comment by GlennRicaud** [comment]
Not a gradle plugin problem.
Upgrading gradle to >=4.2.1 fixes the problem

I close this issue
