### ISSUE TITLE
Adapt to distro renaming and other 7.0.0 changes

### ISSUE THREAD

**Issue by GlennRicaud** [enonic/xp-gradle-plugin#17]
'com.enonic.xp:distro' has been renamed to 'com.enonic.xp:enonic-xp-generic'
Adapt and release a new major release of the plugin

**Comment by jsi** [comment]
Adapting the new names from distro is not good enough.  We need to upgrade the plugin to work with gradle 5.0 as well.  That requires a lot of work.

**Comment by jsi** [comment]
Changed the title, because there are several issues in XP 7.0.0 that we need to accomodate:
 - Gradle 5 (and doing things in a way that worked, but was deprecated in gradle 4.10 as well).
 - Java 11

**Comment by jsi** [comment]
Work in app-contentstudio is done in issue #103 : enonic/app-contentstudio#103.
