### ISSUE TITLE
Support webjar dependencies in base plugin

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp-gradle-plugin#21]
In order to add a webjar as a dependency one must use 'com.enonic.xp.app' plugin. This seems like a strange limitation, it should be allowed via 'com.enonic.xp.base' plugin, for example if one wants to use webjars to build a lib.

**Comment by rymsha** [comment]
webjars dependency contents go straight to assets folder in app - this is the only mission for `webjar` configuration. 
Good practice that lib should not enforce assets for apps using it. If lib does so, it is almost like an "app", and using app plugin for it  is not that strange.
