### ISSUE TITLE
Remove jar version number from file when using deploy task

### ISSUE THREAD

**Issue by sigdestad** [enonic/xp-gradle-plugin#24]
This currently causes problems with people copying multiple versions of the app into the deploy folder. Stripping away version will fix issue.

https://discuss.enonic.com/t/duplicate-loading-of-applications-in-xp7/2151/3

Prepare this fix for 2.1.0 of the plugin

**Comment by rymsha** [comment]
It won't be only for `deploy`. Basically what I initially planed is described here:
https://discuss.gradle.org/t/how-do-i-get-rid-of-version-numbers-and-unspecified-on-java-plugin-jars/7512/2 (slightly outdated, but still works)

Another idea, @sigdestad , maybe we could just recommend people to use the following tiny code in `build.gradle`?

```
jar {
    archiveVersion.set(null)
}
```

This way people have full control if they want the version on jar or not.

We could also update cli so it generates this snippet by default.

**Comment by sigdestad** [comment]
Interesting proposal, but when publishing jars to archives I think it is preferrable to keep the version number. What are your thoughts on that?

**Comment by rymsha** [comment]
Jar is "archive" (because it is just zip) 
Gradle changed `jar.verision =...` syntax to `jar.archiveVersion.set(...)` in 5.1 without changing functionality.

It doesn't affect how it gets published to maven, by the way. In maven it is still versioned
