### ISSUE TITLE
Gradle plugin adds local project path to the Manifest file

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp-gradle-plugin#48]
Gradle plugin adds **local** project path to the Manifest file:

![image](https://user-images.githubusercontent.com/11612490/101908198-0218c400-3bbc-11eb-9caa-0ceb6f7744b9.png)

When an app is installed from the Market and XP is running in dev mode, XP will run the application from source path instead of the installed version.

Basically, with current behaviour you will never be able to run a version from the Market if your local version is different, unless you stop dev mode.

**Comment by alansemenov** [comment]
The idea is good - you should be able to hot-redeploy your local app in dev mode - but not when the app is installed from the Market.

**Comment by rymsha** [comment]
Proposed solution:
- introduce a new gradle property `com.enonic.xp.app.production`. `false` by default.
- if set to `true` - don't include extra source paths
- gradle-defaults plugin verifies than is is set to true when publishing (configurable)
- change all automations that do publishing to specify this value as `true`
