### ISSUE TITLE
Set duplicatesStrategy in UnpackWebJarTask

### ISSUE THREAD

**Issue by alansemenov** [enonic/xp-gradle-plugin#91]
Initiated by https://github.com/enonic/starter-webpack/issues/318#issuecomment-1007318558 and probably related to https://github.com/enonic/xp-gradle-plugin/issues/84.

Some webjars cause the following error after upgrade to Gradle 7:

```
* What went wrong:
Execution failed for task ':unpackWebJars'.
> Entry META-INF/MANIFEST.MF is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.3.1/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.
```

We have fixed it in https://github.com/enonic/starter-bootstrap3 by switching to a different webjar, but it might be an issue with other webjars.

**Comment by rymsha** [comment]
#84 fixes the problem as there is no unpackWebJars task anymore (files are copied directly)
